services:
  db:
    build:
      context: ./scripts
      dockerfile: Dockerfile 
    container_name: preseeded-postgres-db
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-app 
    ports: 
      - "8000:8000"
    depends_on:
      - db
    environment: 
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: devuser
      DB_PASSWORD: devpassword
      DB_NAME: devdb

volumes:
  postgres-db: